export const ADD_ITEM = "ADD_ITEM";
export const DELETE_ITEM = "DELETE_ITEM";
export const typeData = {
    GET_MENUE_DATA_SUCSESS: "GET_MENUE_DATA_SUCSESS",
    GET_MENUE_DATA_ERROR: "GET_MENUE_DATA_ERROR",

    ADD_MENU_DATA_SUCCESS: "ADD_MENU_DATA_SUCCESS",
    ADD_MENU_DATA_ERROR: "ADD_MENU_DATA_ERROR",

    DELETE_MENU_DATA_SUCCESS: "DELETE_MENU_DATA_SUCCESS",
    DELETE_MENU_DATA_ERROR: "DELETE_MENU_DATA_ERROR",

    UPDATE_MENU_DATA_SUCCESS:"UPDATE_MENU_DATA_SUCCESS",
    UPDATE_MENU_DATA_ERROR:"UPDATE_MENU_DATA_ERROR"
} 