export const ADD_ITEM = "ADD_ITEM";
export const DELETE_ITEM = "DELETE_ITEM";
export const typeData = {
    SET_TASTE_DATA_SUCSESS:"SET_TASTE_DATA_SUCSESS",
    
    GET_MENUE_DATA_SUCSESS: "GET_MENUE_DATA_SUCSESS",
    GET_MENUE_DATA_ERROR: "GET_MENUE_DATA_ERROR",

    GET_CUSTOMER_DATA_SUCSESS: "GET_CUSTOMER_DATA_SUCSESS",
    GET_CUSTOMER_DATA_ERROR: "GET_CUSTOMER_DATA_ERROR",

    ADD_MENU_DATA_SUCCESS: "ADD_MENU_DATA_SUCCESS",
    ADD_MENU_DATA_ERROR: "ADD_MENU_DATA_ERROR",

    DELETE_MENU_DATA_SUCCESS: "DELETE_MENU_DATA_SUCCESS",
    DELETE_MENU_DATA_ERROR: "DELETE_MENU_DATA_ERROR",

    UPDATE_MENU_DATA_SUCCESS:"UPDATE_MENU_DATA_SUCCESS",
    UPDATE_MENU_DATA_ERROR:"UPDATE_MENU_DATA_ERROR",

    OTP_GENRATE_ACCOUNT:"OTP_GENRATE_ACCOUNT",
    OTP_GENRATE_ERROR:"OTP_GENRATE_ERROR",

    CREATE_SIGNUP_ACCOUNT:"CREATE_SIGNUP_ACCOUNT",
    CREATE_SIGNUP_ERROR:"CREATE_SIGNUP_ERROR",

    SUBMIT_LOGIN_ACCOUNT:"SUBMIT_LOGIN_ACCOUNT",
    SUBMIT_LOGIN_ERROR:"SUBMIT_LOGIN_ERROR"
    
} 