export const ADD_ITEM = "ADD_ITEM";
export const DELETE_ITEM = "DELETE_ITEM";
export const typeData = {
    GET_MENUE_DATA_SUCSESS: "GET_MENUE_DATA_SUCSESS",
    GET_MENUE_DATA_ERROR: "GET_MENUE_DATA_ERROR"
} 